using WMiIApp.Models;

namespace WMiIApp
{
    public partial class App : Application
    {
        public static RoomMap GlobalRooms { get; } = new RoomMap();

        public static PathFinder pathFinder = new PathFinder();

        //Piwnica
        Room klubStudencki = new Room("klubStudencki", "Klub Studencki/A015 (Piwnica)", 94, 150, -1);
        Room wcPiwnica = new Room("wcPiwnica", "WC Piwnica/A013/A014 (Piwnica)", 105, 150, -1);
        Room bar = new Room("bar", "Bar/A002 (Piwnica)", 135, 150, -1);
        Room schodyParterPiwnica = new Room("schody_parter_piwnica", "Schody do piwnicy (Piwnica)", 170, 149, -1);
        Room schodyParterPiwnicaLesk = new Room("schody_parter_kolo_wejscia", "Schody Piwnica/Parter/I piętro (Piwnica)", 215, 184, -1);
        Room lesk = new Room("lesk", "LESK (Piwnica)", 190, 184, -1);

        //Parter
        Room e106 = new Room("e106", "E106 (Parter)", 239, 233, 0);
        Room e107 = new Room("e107", "E107 (Parter)", 239, 226, 0);
        Room e109 = new Room("e109", "E109 (Parter)", 239, 218, 0);
        Room e111 = new Room("e111", "E111 (Parter)", 239, 210, 0);
        Room wc3 = new Room("wc3", "WC Koło S3 (Parter)", 250, 247, 0);
        Room s3 = new Room("s3", "S3/E103 (Parter)", 250, 229, 0);
        Room s2 = new Room("s2", "S2/E102 (Parter)", 250, 210, 0);
        Room s1 = new Room("s1", "S1/E101 (Parter)", 250, 193, 0);
        Room portiernia = new Room("portiernia", "Portiernia (Parter)", 250, 183, 0);
        Room wejscie = new Room("wejscie", "Wejście (Parter)", 250, 163, 0);
        Room schodyParterPiwnicaLeskKoloWejscia = new Room("schody_parter_kolo_wejscia_parter", "Schody koło wejścia (Parter)", 215, 184, 0);
        Room schodyParterPiwnicaKoloPatio = new Room("schody_parter_piwnica_parter", "Schody do Piwnicy (Parter)", 170, 149, 0);
        Room d114 = new Room("d114", "D114 (Parter)", 250, 135, 0);
        Room d113 = new Room("d113", "D113 (Parter)", 250, 126, 0);
        Room d112 = new Room("d112", "D112 (Parter)", 250, 117, 0);
        Room d111 = new Room("d111", "D111 (Parter)", 250, 107, 0);
        Room d110 = new Room("d110", "D110 (Parter)", 250, 92, 0);
        Room d109 = new Room("d109", "D109 (Parter)", 250, 69, 0);
        Room d108 = new Room("d108", "D108 (Parter)", 250, 59, 0);
        Room d107 = new Room("d107", "D107 (Parter)", 250, 49, 0);
        Room schody3 = new Room("schody3", "Schody Koło Biblioteki (Parter)", 241, 74, 0);
        Room biblioteka = new Room("biblioteka", "Biblioteka/C114 (Parter)", 205, 98, 0);
        Room patio2 = new Room("patio2", "Winda (Parter)", 205, 77, 0);
        Room galeria = new Room("galeria", "Galeria (Parter)", 186, 139, 0);
        Room patio = new Room("patio", "Patio Wejście Koło Szatni", 186, 139, 0);
        Room b124 = new Room("b124", "B124 (Parter)", 55, 134, 0);
        Room b123 = new Room("b123", "B123 (Parter)", 55, 114, 0);
        Room b122 = new Room("b122", "B122 (Parter)", 55, 105, 0);
        Room b121 = new Room("b121", "B121 (Parter)", 55, 95, 0);
        Room b120 = new Room("b120", "B120 (Parter)", 55, 85, 0);
        Room b119 = new Room("b119", "B119 (Parter)", 55, 73, 0);
        Room aula = new Room("aula", "Aula/A105 (Parter)", 66, 200, 0);
        Room salaKonferencyjna = new Room("sala_konferencyjna", "Sala Konferencyjna/A109 (Parter)", 66, 158, 0);
        Room schodyKoloAuli = new Room("schody_kolo_auli", "Schody Koło Auli (Parter)", 54, 141, 0);
        Room wc2 = new Room("wc2", "WC Koło Auli (Parter)", 50, 135, 0);
        Room b106 = new Room("b106", "B106 (Parter)", 50, 129, 0);
        Room b107 = new Room("b107", "B107 (Parter)", 50, 122, 0);
        Room b108 = new Room("b108", "B108 (Parter)", 49, 114, 0);
        Room b109 = new Room("b109", "B109 (Parter)", 50, 105, 0);
        Room b110 = new Room("b110", "B110 (Parter)", 50, 95, 0);
        Room b111 = new Room("b111", "B111 (Parter)", 50, 85, 0);
        Room wc = new Room("wc", "WC Koło L13/C108/C109/C111 (Parter)", 205, 58, 0);
        Room l13 = new Room("l13", "L13/C107 (Parter)", 180, 58, 0);
        Room c106 = new Room("c106", "C106 (Parter)", 135, 58, 0);
        Room c104 = new Room("c104", "C104 (Parter)", 120, 58, 0);
        Room c102 = new Room("c102", "C102 (Parter)", 105, 58, 0);
        Room schody = new Room("schody", "Schody Koło PM1 (Parter)", 85, 58, 0);
        Room pm1 = new Room("pm1", "PM1/B116 (Parter)", 55, 58, 0);
        Room ss1 = new Room("ss1", "SS1/B114 (Parter)", 50, 62, 0);


        //I pietro
        Room f209 = new Room("f209", "F209 (I piętro)", 216, 271, 1);
        Room f208 = new Room("f208", "F208 (I piętro)", 222, 271, 1);
        Room f207 = new Room("f207", "F207 (I piętro)", 230, 271, 1);
        Room f206 = new Room("f206", "F206 (I piętro)", 245, 271, 1);
        Room f205 = new Room("f205", "F205 (I piętro)", 256, 271, 1);
        Room f204 = new Room("f204", "F204 (I piętro)", 265, 271, 1);
        Room wc2IPietro = new Room("wc2_IPietro", "WC Koło S4 (I piętro)", 248, 250, 1);
        Room e207 = new Room("e207", "E207 (I piętro)", 250, 242, 1);
        Room e204 = new Room("e204", "E204 (I piętro)", 250, 233, 1);
        Room e203 = new Room("e203", "E203 (I piętro)", 250, 226, 1);
        Room e202 = new Room("e202", "E202 (I piętro)", 250, 218, 1);
        Room s4 = new Room("s4", "S4/E201 (I piętro)", 250, 206, 1);
        Room e211 = new Room("e211", "E211 (I piętro)", 242, 242, 1);
        Room e212 = new Room("e212", "E212 (I piętro)", 242, 234, 1);
        Room e213 = new Room("e213", "E213 (I piętro)", 242, 226, 1);
        Room e214 = new Room("e214", "E214 (I piętro)", 242, 220, 1);
        Room spot = new Room("spot", "Sala Spotkań/E216 (I piętro)", 242, 205, 1);
        Room schodyKoloWejsciaPierwszePietro = new Room("schody_parter_kolo_wejscia_pierwsze", "Schody koło wejścia (I piętro)", 234, 192, 1);
        Room schodyPierwszeDrugiePietroPierwsze = new Room("schody_pierwsze_drugie_pietro", "Schody I piętro - II piętro (I piętro)", 252, 192, 1);
        Room dziekanat = new Room("dziekanat", "Dziekanat/D214/D210/D208 (I piętro)", 252, 152, 1);
        Room dziekanatStudencki = new Room("dziekanat_studencki", "Dziekanat studencki/D219/D221 (I piętro)", 240, 120, 1);
        Room s5 = new Room("s5", "S5/D206; (I piętro)", 252, 118, 1);
        Room s6 = new Room("s6", "S6/D204 (I piętro)", 252, 92, 1);
        Room s7 = new Room("s7", "S7/D203 (I piętro)", 252, 71, 1);
        Room s8 = new Room("s8", "S8/D202 (I piętro)", 248, 46, 1);
        Room korytarzPierwszePietro = new Room("korytarz_pierwsze_pietro", "Winda (I piętro)", 200, 92, 1);
        Room schodyPierwszePietroKoloS8 = new Room("schody2", "Schody obok S8 (I piętro)", 243, 68, 1);
        Room b217 = new Room("b217", "B217 (I piętro)", 55, 55, 1);
        Room b218 = new Room("b218", "B218 (I piętro)", 55, 64, 1);
        Room b219 = new Room("b219", "B219 (I piętro)", 55, 72, 1);
        Room b220 = new Room("b220", "B220 (I piętro)", 55, 81, 1);
        Room b221 = new Room("b221", "B221 (I piętro)", 55, 90, 1);
        Room b222 = new Room("b222", "B222 (I piętro)", 55, 98, 1);
        Room b223 = new Room("b223", "B223 (I piętro)", 55, 105, 1);
        Room b224 = new Room("b224", "B224 (I piętro)", 55, 116, 1);
        Room schodyKoloAuliPierwsze = new Room("schody_kolo_auli_pierwsze", "Schody koło Auli (I piętro)", 52, 125, 1);
        Room b202 = new Room("b202", "B202 (I piętro)", 48, 117, 1);
        Room b203 = new Room("b203", "B203 (I piętro)", 48, 112, 1);
        Room b204 = new Room("b204", "B204 (I piętro)", 48, 102, 1);
        Room b205 = new Room("b205", "B205 (I piętro)", 48, 95, 1);
        Room b206 = new Room("b206", "B206 (I piętro)", 48, 86, 1);
        Room b207 = new Room("b207", "B207 (I piętro)", 48, 76, 1);
        Room b208 = new Room("b208", "B208 (I piętro)", 48, 66, 1);
        Room wcPierwsze = new Room("wc_pierwsze", "WC Koło L12/C205/C206/C208 (I piętro)", 200, 40, 1);
        Room l12 = new Room("l12", "L12/C204 (I piętro)", 180, 40, 1);
        Room l11 = new Room("l11", "L11/C203 (I piętro)", 140, 40, 1);
        Room l10 = new Room("l10", "L10/C202 (I piętro)", 110, 40, 1);
        Room schodyPierwszePietroKoloPM2 = new Room("schody_pierwsze", "Schody obok PM2 (I piętro)", 80, 40, 1);
        Room pm2 = new Room("pm2", "PM2/B213 (I piętro)", 60, 40, 1);
        Room ss2 = new Room("ss2", "SS2/B211 (I piętro)", 48, 40, 1);
        Room f105 = new Room("f105", "F105 (Parter/I piętro) Zejdź na dół schodami", 230, 250, 1);
        Room f107 = new Room("f107", "F107 (Parter/I piętro) Zejdź na dół schodami", 230, 250, 1);
        Room f108 = new Room("f107", "F108 (Parter/I piętro) Zejdź na dół schodami", 230, 250, 1);


        //II pietro
        Room l9 = new Room("l9", "L9/E305 (II piętro)", 248, 240, 2);
        Room l8 = new Room("l8", "L8/E302 (II piętro)", 248, 225, 2);
        Room l7 = new Room("l7", "L7/E301 (II piętro)", 248, 208, 2);
        Room schodyPierwszeDrugiePietroDrugie = new Room("schody_pierwsze_drugie_pietro_drugie", "Schody I piętro - II piętro (II piętro)", 249, 154, 2);
        Room e307 = new Room("e307", "E307 (II piętro)", 240, 233, 2);
        Room e309 = new Room("e309", "E309 (II piętro)", 240, 225, 2);
        Room e310 = new Room("e310", "E310 (II piętro)", 240, 217, 2);
        Room e311 = new Room("e311", "E311 (II piętro)", 240, 209, 2);
        Room e312 = new Room("e312", "E312 (II piętro)", 240, 201, 2);
        Room d307 = new Room("d307", "D307 (II piętro)", 240, 192, 2);
        Room d308 = new Room("d308", "D308 (II piętro)", 240, 184, 2);
        Room d309 = new Room("d309", "D309 (II piętro)", 240, 176, 2);
        Room d310 = new Room("d310", "D310 (II piętro)", 240, 167, 2);
        Room d311 = new Room("d311", "D311 (II piętro)", 240, 159, 2);
        Room d312 = new Room("d312", "D312 (II piętro)", 240, 151, 2);
        Room d313 = new Room("d313", "D313 (II piętro)", 240, 143, 2);
        Room d314 = new Room("d314", "D314 (II piętro)", 240, 135, 2);
        Room l6 = new Room("l6", "L6/D305 (II piętro)", 248, 142, 2);
        Room l5 = new Room("l5", "L5/D304 (II piętro)", 248, 125, 2);
        Room l4 = new Room("l4", "L4/D303 (II piętro)", 248, 110, 2);
        Room s9 = new Room("s9", "S9/D302 (II piętro)", 243, 108, 2);
        Room schodyKoloS9 = new Room("schody_kolo_s9", "Schody koło S9 (II piętro)", 230, 108, 2);
        Room korytarzDrugiePietro = new Room("korytarz_drugie_pietro", "Winda (II piętro)", 200, 115, 2);
        Room b317 = new Room("b317", "B317 (II piętro)", 54, 82, 2);
        Room b318 = new Room("b318", "B318 (II piętro)", 54, 90, 2);
        Room b319 = new Room("b319", "B319 (II piętro)", 54, 100, 2);
        Room b320 = new Room("b320", "B320 (II piętro)", 54, 108, 2);
        Room b321 = new Room("b321", "B321 (II piętro)", 54, 116, 2);
        Room b322 = new Room("b322", "B322 (II piętro)", 54, 125, 2);
        Room b323 = new Room("b323", "B323 (II piętro)", 54, 134, 2);
        Room b324 = new Room("b324", "B324 (II piętro)", 54, 144, 2);
        Room schodyKoloAuliDrugie = new Room("schody_kolo_auli_drugie", "Schody koło Auli (II piętro)", 52, 155, 2);
        Room b302 = new Room("b302", "B302 (II piętro)", 48, 146, 2);
        Room b303 = new Room("b303", "B303 (II piętro)", 48, 140, 2);
        Room b304 = new Room("b304", "B304 (II piętro)", 48, 132, 2);
        Room b305 = new Room("b305", "B305 (II piętro)", 48, 124, 2);
        Room b306 = new Room("b306", "B306 (II piętro)", 48, 115, 2);
        Room b307 = new Room("b307", "B307 (II piętro)", 48, 105, 2);
        Room b308 = new Room("b308", "B308 (II piętro)", 48, 95, 2);
        Room wcDrugiePietro = new Room("wc_drugie_pietro", "WC Koło L3/C305/C306/C308 (II piętro)", 200, 74, 2);
        Room l3 = new Room("l3", "L3/C304 (II piętro)", 178, 74, 2);
        Room l2 = new Room("l2", "L2/C303 (II piętro)", 146, 74, 2);
        Room l1 = new Room("l1", "L1/C302 (II piętro)", 110, 74, 2);
        Room schodyKoloPM3 = new Room("schody_kolo_pm3", "Schody koło PM3 (II piętro)", 82, 74, 2);
        Room pm3 = new Room("pm3", "PM3/B313 (II piętro)", 54, 74, 2);
        Room ss3 = new Room("ss3", "SS3/B311 (II piętro)", 48, 74, 2);
        Room f303 = new Room("f303", "F303 (I piętro/II piętro) Zejdź na dół schodami", 235, 245, 2);
        Room f305 = new Room("f305", "F305 (I piętro/II piętro) Zejdź na dół schodami", 235, 245, 2);
        Room f306 = new Room("f306", "F306 (I piętro/II piętro) Zejdź na dół schodami", 235, 245, 2);
        Room f403 = new Room("f403", "F403 (II piętro)", 255, 260, 2);
        Room f405 = new Room("f405", "F405 (II piętro)", 235, 260, 2);

        public App()
        {
            InitializeComponent();

            addNeighborsToRooms();

            addRoomsToVector();

            addResidentsToRooms();

            MainPage = new AppShell();
        }

        public void addResidentsToRooms()
        {
            b224.AddResident("dr Przemysław Berk");
            b120.AddResident("dr Jerzy Białkowski");
            e203.AddResident("dr Bartosz Bieganowski");
            d107.AddResident("prof. dr hab. Grzegorz Bobiński");
            b108.AddResident("dr Rafał Bocian");
            e311.AddResident("dr Dariusz Borkowski");
            b107.AddResident("dr Wojciech Bułatek");
            e310.AddResident("dr Michał Chlebiej");
            b224.AddResident("dr Welington Cordeiro");
            b204.AddResident("dr Klaudiusz Czudek");
            f208.AddResident("dr hab. Aleksander Ćwiszewski, prof. UMK");
            d111.AddResident("prof. dr hab. Piotr Dowbor");
            b204.AddResident("dr Aurelia Dymek");
            b318.AddResident("dr Adrian Falkowski");
            b219.AddResident("prof. dr hab. Krzysztof Frączek");
            e214.AddResident("dr Dorota Gabor");
            d108.AddResident("dr Marcin Gąsiorek");
            d308.AddResident("dr Anna Gogolińska");
            b217.AddResident("dr Anna Gołębiewska");
            b218.AddResident("prof. dr hab. Oleksandr Gomilko");
            b307.AddResident("dr hab. Agnieszka Goroncy, prof. UMK");
            b119.AddResident("dr Adam Hajduk");
            b321.AddResident("prof. dr hab. Adam Jakubowski");
            b305.AddResident("dr Krzysztof Jasiński");
            d109.AddResident("dr Alicja Jaworska-Pastuszak");
            d109.AddResident("dr Mariusz Kaniecki");
            b319.AddResident("dr Joanna Karłowska-Pik");
            d110.AddResident("prof. dr hab. Stanisław Kasjan");
            b320.AddResident("dr hab. Tomasz Klimsiak, prof. UMK");
            f206.AddResident("dr Maria Kobus");
            b124.AddResident("dr hab. Justyna Kosakowska, prof. UMK");
            b207.AddResident("dr Marta Kowalczyk");
            b121.AddResident("dr Witold Kraśkiewicz");
            f209.AddResident("dr Agnieszka Krause");
            b223.AddResident("dr hab. Joanna Kułaga-Przymus, prof. UMK");
            d309.AddResident("mgr Damian Kurpiewski");
            b109.AddResident("dr Anna Beata Kwiatkowska");
            b221.AddResident("prof. dr hab. Mariusz Lemańczyk");
            e202.AddResident("dr Mateusz Maciejewski");
            d114.AddResident("dr hab. Piotr Malicki, prof. UMK");
            d311.AddResident("mgr Dawid Maliszewski");
            f205.AddResident("dr hab. Mieczysław K. Mentzen, prof. UMK");
            d307.AddResident("dr Łukasz Mikulski");
            b119.AddResident("dr hab. Andrzej Mróz, prof. UMK");
            e307.AddResident("dr Jakub Narębski");
            b304.AddResident("prof. dr hab. Wojciech Niemiro");
            e307.AddResident("dr Marek Nowicki");
            e111.AddResident("dr Grzegorz Pastuszak");
            e309.AddResident("dr Marcin Piątkowski");
            b122.AddResident("prof. dr hab. Zygmunt Pogorzały");
            b111.AddResident("mgr Andrzej Polewczyński");
            b305.AddResident("dr hab. Wojciech Rejchel, prof. UMK");
            b322.AddResident("prof. dr hab. Andrzej Rozkosz");
            d308.AddResident("mgr Andrzej Rutkowski");
            b206.AddResident("prof. dr hab. Sławomir Rybicki");
            b317.AddResident("mgr Renata Rychlicka");
            b204.AddResident("dr Łukasz Rzepnicki");
            b318.AddResident("dr Maurycy Rzymowski");
            b110.AddResident("dr Andrzej Sendlewski");
            e203.AddResident("dr Jakub Siemianowski");
            b208.AddResident("dr Robert Skiba");
            d311.AddResident("dr Mirosława Skowrońska");
            e111.AddResident("dr Adam Skowyrski");
            b323.AddResident("prof. dr hab. Leszek Słomiński");
            b207.AddResident("dr Piotr Stefaniak");
            b208.AddResident("dr Daniel Strzelecki");
            b324.AddResident("dr hab. Zbigniew Szewczak, prof. UMK");
            b317.AddResident("mgr Dorota Szreder");
            b107.AddResident("dr Jerzy Szymański");
            b307.AddResident("dr Mateusz Topolewski");
            e309.AddResident("dr hab. Piotr Wiśniewski, prof. UMK");
            f209.AddResident("dr Magdalena Wysokińska-Pliszka");
            b306.AddResident("dr hab. Aleksander Zaigrajew, prof. UMK");
            d108.AddResident("dr Katarzyna Zając");
            b319.AddResident("dr Bartosz Ziemkiewicz");
            b123.AddResident("prof. dr hab. Grzegorz Zwara");
            e311.AddResident("dr Błażej Zyglarski");
            f105.AddResident("dr Piotr Kokocki");
            f105.AddResident("dr Krzysztof Leśniak");
            f107.AddResident("dr hab. Janusz Zieliński, prof. UMK");
            f108.AddResident("mgr Kamil Palusiński");
            f303.AddResident("dr Danuta Katafias");
            f305.AddResident("dr hab. Piotr Jędrzejewicz, prof. UMK");
            f306.AddResident("dr hab. Grzegorz Gabor, prof. UMK");
            f403.AddResident("dr Kamila Barylska");
            f403.AddResident("dr Aleksandra Boniewicz");
            f403.AddResident("dr Marta Burzańska");
            f405.AddResident("dr Krzysztof Rykaczewski");
            f405.AddResident("dr Piotr Przymus");
        }

        public void addOtherNamesToRooms()
        {
            bar.AddOtherName("A002");
            klubStudencki.AddOtherName("A015");
            wcPiwnica.AddOtherName("A013");
            wcPiwnica.AddOtherName("A014");

            salaKonferencyjna.AddOtherName("A109");
            aula.AddOtherName("A105");
            ss1.AddOtherName("B114");
            pm1.AddOtherName("B116");
            l13.AddOtherName("C107");
            wc.AddOtherName("C108");
            wc.AddOtherName("C109");
            wc.AddOtherName("C111");
            biblioteka.AddOtherName("C114");
            s1.AddOtherName("E101");
            s2.AddOtherName("E102");
            s3.AddOtherName("E103");

            dziekanat.AddOtherName("D214");
            dziekanat.AddOtherName("D210");
            dziekanat.AddOtherName("D208");
            dziekanatStudencki.AddOtherName("D219");
            dziekanatStudencki.AddOtherName("D221");
            s5.AddOtherName("D206");
            s6.AddOtherName("D204");
            s7.AddOtherName("D203");
            s8.AddOtherName("D202");
            l12.AddOtherName("C204");
            wcPierwsze.AddOtherName("C205");
            wcPierwsze.AddOtherName("C206");
            wcPierwsze.AddOtherName("C208");
            l11.AddOtherName("C203");
            l10.AddOtherName("C202");
            pm2.AddOtherName("B213");
            ss2.AddOtherName("B211");
            spot.AddOtherName("E216");
            s4.AddOtherName("E201");

            l7.AddOtherName("E301");
            l8.AddOtherName("E302");
            l9.AddOtherName("E305");
            l6.AddOtherName("D305");
            l5.AddOtherName("D304");
            l4.AddOtherName("D303");
            s9.AddOtherName("D302");
            wcDrugiePietro.AddOtherName("C305");
            wcDrugiePietro.AddOtherName("C306");
            wcDrugiePietro.AddOtherName("C308");
            l3.AddOtherName("C304");
            l2.AddOtherName("C303");
            l1.AddOtherName("C302");
            pm3.AddOtherName("B313");
            ss3.AddOtherName("B311");

        }

        public void addNeighborsToRooms()
        {
            //Sasiedzi piwnica
            klubStudencki.AddNeighbor(wcPiwnica);
            wcPiwnica.AddNeighbor(bar);
            wcPiwnica.AddNeighbor(klubStudencki);
            bar.AddNeighbor(wcPiwnica);
            bar.AddNeighbor(schodyParterPiwnica);
            schodyParterPiwnica.AddNeighbor(bar);
            schodyParterPiwnica.AddNeighbor(schodyParterPiwnicaKoloPatio);
            schodyParterPiwnicaLesk.AddNeighbor(schodyParterPiwnicaLeskKoloWejscia);
            schodyParterPiwnicaLesk.AddNeighbor(lesk);
            lesk.AddNeighbor(schodyParterPiwnicaLesk);

            //Sasiedzi parter
            e106.AddNeighbor(e107);
            e106.AddNeighbor(s3);
            e106.AddNeighbor(wc3);
            e107.AddNeighbor(e109);
            e107.AddNeighbor(e106);
            e107.AddNeighbor(s3);
            e109.AddNeighbor(e111);
            e109.AddNeighbor(e107);
            e109.AddNeighbor(s2);
            e111.AddNeighbor(e109);
            e111.AddNeighbor(s2);
            e111.AddNeighbor(s1);
            wc3.AddNeighbor(e106);
            wc3.AddNeighbor(s3);
            s3.AddNeighbor(wc3);
            s3.AddNeighbor(e106);
            s3.AddNeighbor(e107);
            s3.AddNeighbor(s2);
            s2.AddNeighbor(e111);
            s2.AddNeighbor(e109);
            s2.AddNeighbor(s1);
            s2.AddNeighbor(s3);
            s1.AddNeighbor(s2);
            s1.AddNeighbor(e111);
            s1.AddNeighbor(portiernia);
            portiernia.AddNeighbor(s1);
            portiernia.AddNeighbor(schodyParterPiwnicaLeskKoloWejscia);
            portiernia.AddNeighbor(wejscie);
            portiernia.AddNeighbor(galeria);
            wejscie.AddNeighbor(d114);
            wejscie.AddNeighbor(portiernia);
            wejscie.AddNeighbor(schodyParterPiwnicaLeskKoloWejscia);
            wejscie.AddNeighbor(galeria);
            schodyParterPiwnicaLeskKoloWejscia.AddNeighbor(schodyParterPiwnicaLesk);
            schodyParterPiwnicaLeskKoloWejscia.AddNeighbor(wejscie);
            schodyParterPiwnicaLeskKoloWejscia.AddNeighbor(portiernia);
            schodyParterPiwnicaLeskKoloWejscia.AddNeighbor(galeria);
            schodyParterPiwnicaLeskKoloWejscia.AddNeighbor(schodyKoloWejsciaPierwszePietro);
            schodyParterPiwnicaKoloPatio.AddNeighbor(schodyParterPiwnica);
            schodyParterPiwnicaKoloPatio.AddNeighbor(galeria);
            schodyParterPiwnicaKoloPatio.AddNeighbor(patio);
            schodyParterPiwnicaKoloPatio.AddNeighbor(salaKonferencyjna);
            schodyParterPiwnicaKoloPatio.AddNeighbor(aula);
            d114.AddNeighbor(wejscie);
            d114.AddNeighbor(d113);
            d113.AddNeighbor(d114);
            d113.AddNeighbor(d112);
            d112.AddNeighbor(d111);
            d112.AddNeighbor(d113);
            d111.AddNeighbor(d112);
            d111.AddNeighbor(biblioteka);
            d111.AddNeighbor(d110);
            d110.AddNeighbor(d111);
            d110.AddNeighbor(schody3);
            d110.AddNeighbor(biblioteka);
            d109.AddNeighbor(schody3);
            d109.AddNeighbor(d108);
            d108.AddNeighbor(d109);
            d108.AddNeighbor(d107);
            d107.AddNeighbor(d108);
            schody3.AddNeighbor(d109);
            schody3.AddNeighbor(d110);
            schody3.AddNeighbor(schodyPierwszePietroKoloS8);
            biblioteka.AddNeighbor(galeria);
            biblioteka.AddNeighbor(patio2);
            biblioteka.AddNeighbor(d111);
            biblioteka.AddNeighbor(d110);
            patio2.AddNeighbor(biblioteka);
            patio2.AddNeighbor(wc);
            patio2.AddNeighbor(korytarzPierwszePietro);
            galeria.AddNeighbor(biblioteka);
            galeria.AddNeighbor(wejscie);
            galeria.AddNeighbor(schodyParterPiwnicaLeskKoloWejscia);
            galeria.AddNeighbor(schodyParterPiwnicaKoloPatio);
            galeria.AddNeighbor(portiernia);
            patio.AddNeighbor(salaKonferencyjna);
            patio.AddNeighbor(schodyKoloAuli);
            patio.AddNeighbor(schodyParterPiwnicaKoloPatio);
            patio.AddNeighbor(aula);
            b124.AddNeighbor(schodyKoloAuli);
            b124.AddNeighbor(wc2);
            b124.AddNeighbor(b106);
            b123.AddNeighbor(b107);
            b123.AddNeighbor(b108);
            b123.AddNeighbor(b122);
            b123.AddNeighbor(b109);
            b122.AddNeighbor(b123);
            b122.AddNeighbor(b109);
            b122.AddNeighbor(b121);
            b122.AddNeighbor(b110);
            b122.AddNeighbor(b108);
            b121.AddNeighbor(b110);
            b121.AddNeighbor(b111);
            b121.AddNeighbor(b120);
            b121.AddNeighbor(b122);
            b121.AddNeighbor(b109);
            b120.AddNeighbor(b121);
            b120.AddNeighbor(b119);
            b120.AddNeighbor(b110);
            b120.AddNeighbor(b111);
            b119.AddNeighbor(b120);
            b119.AddNeighbor(b111);
            b119.AddNeighbor(ss1);
            b119.AddNeighbor(pm1);
            aula.AddNeighbor(salaKonferencyjna);
            aula.AddNeighbor(patio);
            aula.AddNeighbor(schodyParterPiwnicaKoloPatio);
            salaKonferencyjna.AddNeighbor(aula);
            salaKonferencyjna.AddNeighbor(patio);
            salaKonferencyjna.AddNeighbor(schodyKoloAuli);
            salaKonferencyjna.AddNeighbor(schodyParterPiwnicaKoloPatio);
            schodyKoloAuli.AddNeighbor(patio);
            schodyKoloAuli.AddNeighbor(salaKonferencyjna);
            schodyKoloAuli.AddNeighbor(wc2);
            schodyKoloAuli.AddNeighbor(b124);
            schodyKoloAuli.AddNeighbor(schodyKoloAuliPierwsze);
            wc2.AddNeighbor(schodyKoloAuli);
            wc2.AddNeighbor(b106);
            wc2.AddNeighbor(b124);
            b106.AddNeighbor(b107);
            b106.AddNeighbor(wc2);
            b106.AddNeighbor(b124);
            b107.AddNeighbor(b106);
            b107.AddNeighbor(b108);
            b107.AddNeighbor(b123);
            b108.AddNeighbor(b123);
            b108.AddNeighbor(b107);
            b108.AddNeighbor(b109);
            b108.AddNeighbor(b122);
            b109.AddNeighbor(b108);
            b109.AddNeighbor(b110);
            b109.AddNeighbor(b123);
            b109.AddNeighbor(b122);
            b109.AddNeighbor(b121);
            b110.AddNeighbor(b109);
            b110.AddNeighbor(b111);
            b110.AddNeighbor(b122);
            b110.AddNeighbor(b121);
            b110.AddNeighbor(b120);
            b111.AddNeighbor(b119);
            b111.AddNeighbor(b120);
            b111.AddNeighbor(b121);
            b111.AddNeighbor(b110);
            b111.AddNeighbor(ss1);
            wc.AddNeighbor(patio2);
            wc.AddNeighbor(l13);
            l13.AddNeighbor(wc);
            l13.AddNeighbor(c106);
            c106.AddNeighbor(l13);
            c106.AddNeighbor(c104);
            c104.AddNeighbor(c106);
            c104.AddNeighbor(c102);
            c102.AddNeighbor(c104);
            c102.AddNeighbor(schody);
            schody.AddNeighbor(pm1);
            schody.AddNeighbor(c102);
            pm1.AddNeighbor(ss1);
            pm1.AddNeighbor(schody);
            ss1.AddNeighbor(pm1);
            ss1.AddNeighbor(b119);
            ss1.AddNeighbor(b111);

            //Sasiedzi I pietro
            f209.AddNeighbor(f208);
            f208.AddNeighbor(f209);
            f208.AddNeighbor(f207);
            f207.AddNeighbor(f208);
            f207.AddNeighbor(f206);
            f207.AddNeighbor(wc2IPietro);
            f207.AddNeighbor(f105);
            f207.AddNeighbor(f107);
            f207.AddNeighbor(f108);
            f105.AddNeighbor(f207);
            f105.AddNeighbor(wc2IPietro);
            f107.AddNeighbor(f207);
            f107.AddNeighbor(wc2IPietro);
            f108.AddNeighbor(f207);
            f108.AddNeighbor(wc2IPietro);
            f206.AddNeighbor(f207);
            f206.AddNeighbor(f205);
            f205.AddNeighbor(f206);
            f205.AddNeighbor(f204);
            f204.AddNeighbor(f205);
            wc2IPietro.AddNeighbor(f207);
            wc2IPietro.AddNeighbor(e211);
            wc2IPietro.AddNeighbor(e207);
            wc2IPietro.AddNeighbor(f105);
            wc2IPietro.AddNeighbor(f107);
            wc2IPietro.AddNeighbor(f108);
            e207.AddNeighbor(wc2IPietro);
            e207.AddNeighbor(e211);
            e207.AddNeighbor(e204);
            e207.AddNeighbor(e212);
            e204.AddNeighbor(e207);
            e204.AddNeighbor(e203);
            e204.AddNeighbor(e213);
            e204.AddNeighbor(e212);
            e204.AddNeighbor(e211);
            e203.AddNeighbor(e202);
            e203.AddNeighbor(e204);
            e203.AddNeighbor(e212);
            e203.AddNeighbor(e213);
            e203.AddNeighbor(e214);
            e202.AddNeighbor(s4);
            e202.AddNeighbor(e203);
            e202.AddNeighbor(spot);
            s4.AddNeighbor(schodyPierwszeDrugiePietroPierwsze);
            s4.AddNeighbor(schodyKoloWejsciaPierwszePietro);
            s4.AddNeighbor(spot);
            s4.AddNeighbor(e202);
            s4.AddNeighbor(e214);
            e211.AddNeighbor(wc2IPietro);
            e211.AddNeighbor(e212);
            e211.AddNeighbor(e207);
            e211.AddNeighbor(e204);
            e212.AddNeighbor(e213);
            e212.AddNeighbor(e211);
            e212.AddNeighbor(e203);
            e212.AddNeighbor(e204);
            e212.AddNeighbor(e207);
            e213.AddNeighbor(e214);
            e213.AddNeighbor(e212);
            e213.AddNeighbor(e203);
            e213.AddNeighbor(e204);
            e213.AddNeighbor(e202);
            e214.AddNeighbor(e213);
            e214.AddNeighbor(spot);
            e214.AddNeighbor(e203);
            e214.AddNeighbor(e202);
            e214.AddNeighbor(s4);
            spot.AddNeighbor(schodyPierwszeDrugiePietroPierwsze);
            spot.AddNeighbor(schodyKoloWejsciaPierwszePietro);
            spot.AddNeighbor(s4);
            spot.AddNeighbor(e214);
            spot.AddNeighbor(e202);
            schodyKoloWejsciaPierwszePietro.AddNeighbor(spot);
            schodyKoloWejsciaPierwszePietro.AddNeighbor(s4);
            schodyKoloWejsciaPierwszePietro.AddNeighbor(schodyParterPiwnicaLeskKoloWejscia);
            schodyKoloWejsciaPierwszePietro.AddNeighbor(dziekanat);
            schodyKoloWejsciaPierwszePietro.AddNeighbor(schodyPierwszeDrugiePietroPierwsze);
            schodyPierwszeDrugiePietroPierwsze.AddNeighbor(schodyKoloWejsciaPierwszePietro);
            schodyPierwszeDrugiePietroPierwsze.AddNeighbor(dziekanat);
            schodyPierwszeDrugiePietroPierwsze.AddNeighbor(spot);
            schodyPierwszeDrugiePietroPierwsze.AddNeighbor(s4);
            schodyPierwszeDrugiePietroPierwsze.AddNeighbor(schodyPierwszeDrugiePietroDrugie);
            dziekanat.AddNeighbor(schodyKoloWejsciaPierwszePietro);
            dziekanat.AddNeighbor(schodyPierwszeDrugiePietroPierwsze);
            dziekanat.AddNeighbor(dziekanatStudencki);
            dziekanat.AddNeighbor(s5);
            dziekanatStudencki.AddNeighbor(s5);
            dziekanatStudencki.AddNeighbor(dziekanat);
            dziekanatStudencki.AddNeighbor(s6);
            s5.AddNeighbor(dziekanat);
            s5.AddNeighbor(dziekanatStudencki);
            s5.AddNeighbor(s6);
            s6.AddNeighbor(dziekanatStudencki);
            s6.AddNeighbor(s5);
            s6.AddNeighbor(s7);
            s6.AddNeighbor(korytarzPierwszePietro);
            s7.AddNeighbor(s8);
            s7.AddNeighbor(schodyPierwszePietroKoloS8);
            s7.AddNeighbor(s6);
            s8.AddNeighbor(schodyPierwszePietroKoloS8);
            s8.AddNeighbor(s7);
            korytarzPierwszePietro.AddNeighbor(s6);
            korytarzPierwszePietro.AddNeighbor(wcPierwsze);
            korytarzPierwszePietro.AddNeighbor(patio2);
            korytarzPierwszePietro.AddNeighbor(korytarzDrugiePietro);
            schodyPierwszePietroKoloS8.AddNeighbor(schody3);
            schodyPierwszePietroKoloS8.AddNeighbor(s7);
            schodyPierwszePietroKoloS8.AddNeighbor(s8);
            schodyPierwszePietroKoloS8.AddNeighbor(schodyKoloS9);
            b217.AddNeighbor(ss2);
            b217.AddNeighbor(pm2);
            b217.AddNeighbor(b208);
            b217.AddNeighbor(b218);
            b218.AddNeighbor(b217);
            b218.AddNeighbor(b219);
            b218.AddNeighbor(b208);
            b219.AddNeighbor(b218);
            b219.AddNeighbor(b220);
            b219.AddNeighbor(b208);
            b219.AddNeighbor(b207);
            b220.AddNeighbor(b219);
            b220.AddNeighbor(b221);
            b220.AddNeighbor(b207);
            b220.AddNeighbor(b206);
            b221.AddNeighbor(b222);
            b221.AddNeighbor(b220);
            b221.AddNeighbor(b206);
            b221.AddNeighbor(b205);
            b222.AddNeighbor(b223);
            b222.AddNeighbor(b221);
            b222.AddNeighbor(b205);
            b222.AddNeighbor(b204);
            b223.AddNeighbor(b224);
            b223.AddNeighbor(b222);
            b223.AddNeighbor(b204);
            b223.AddNeighbor(b203);
            b224.AddNeighbor(b223);
            b224.AddNeighbor(b203);
            b224.AddNeighbor(b202);
            b224.AddNeighbor(schodyKoloAuliPierwsze);
            schodyKoloAuliPierwsze.AddNeighbor(b224);
            schodyKoloAuliPierwsze.AddNeighbor(b202);
            schodyKoloAuliPierwsze.AddNeighbor(schodyKoloAuli);
            schodyKoloAuliPierwsze.AddNeighbor(schodyKoloAuliDrugie);
            b202.AddNeighbor(schodyKoloAuliPierwsze);
            b202.AddNeighbor(b203);
            b202.AddNeighbor(b224);
            b203.AddNeighbor(b224);
            b203.AddNeighbor(b202);
            b203.AddNeighbor(b223);
            b203.AddNeighbor(b204);
            b204.AddNeighbor(b203);
            b204.AddNeighbor(b223);
            b204.AddNeighbor(b222);
            b204.AddNeighbor(b205);
            b205.AddNeighbor(b204);
            b205.AddNeighbor(b222);
            b205.AddNeighbor(b221);
            b205.AddNeighbor(b206);
            b206.AddNeighbor(b205);
            b206.AddNeighbor(b221);
            b206.AddNeighbor(b220);
            b206.AddNeighbor(b207);
            b207.AddNeighbor(b206);
            b207.AddNeighbor(b220);
            b207.AddNeighbor(b219);
            b207.AddNeighbor(b208);
            b208.AddNeighbor(b207);
            b208.AddNeighbor(b219);
            b208.AddNeighbor(b218);
            b208.AddNeighbor(b217);
            b208.AddNeighbor(ss2);
            wcPierwsze.AddNeighbor(korytarzPierwszePietro);
            wcPierwsze.AddNeighbor(l12);
            l12.AddNeighbor(wcPierwsze);
            l12.AddNeighbor(l11);
            l11.AddNeighbor(l12);
            l11.AddNeighbor(l10);
            l10.AddNeighbor(l11);
            l10.AddNeighbor(schodyPierwszePietroKoloPM2);
            schodyPierwszePietroKoloPM2.AddNeighbor(l10);
            schodyPierwszePietroKoloPM2.AddNeighbor(pm2);
            schodyPierwszePietroKoloPM2.AddNeighbor(schody);
            schodyPierwszePietroKoloPM2.AddNeighbor(schodyKoloPM3);
            pm2.AddNeighbor(ss2);
            pm2.AddNeighbor(schodyPierwszePietroKoloPM2);
            pm2.AddNeighbor(b217);
            ss2.AddNeighbor(pm2);
            ss2.AddNeighbor(b217);
            ss2.AddNeighbor(b208);

            //Sasiedzi II pietro
            l9.AddNeighbor(e307);
            l9.AddNeighbor(l8);
            l9.AddNeighbor(f303);
            l9.AddNeighbor(f305);
            l9.AddNeighbor(f306);
            f303.AddNeighbor(l9);
            f303.AddNeighbor(f405);
            f305.AddNeighbor(l9);
            f305.AddNeighbor(f405);
            f306.AddNeighbor(l9);
            f306.AddNeighbor(f405);
            l8.AddNeighbor(e307);
            l8.AddNeighbor(e309);
            l8.AddNeighbor(e310);
            l8.AddNeighbor(l7);
            l7.AddNeighbor(l8);
            l7.AddNeighbor(e312);
            l7.AddNeighbor(e311);
            l7.AddNeighbor(e310);
            schodyPierwszeDrugiePietroDrugie.AddNeighbor(schodyPierwszeDrugiePietroPierwsze);
            schodyPierwszeDrugiePietroDrugie.AddNeighbor(l6);
            schodyPierwszeDrugiePietroDrugie.AddNeighbor(d311);
            schodyPierwszeDrugiePietroDrugie.AddNeighbor(d312);
            e307.AddNeighbor(l9);
            e307.AddNeighbor(e309);
            e307.AddNeighbor(l8);
            e309.AddNeighbor(e310);
            e309.AddNeighbor(e307);
            e309.AddNeighbor(l8);
            e310.AddNeighbor(l7);
            e310.AddNeighbor(l8);
            e310.AddNeighbor(e309);
            e310.AddNeighbor(e311);
            e310.AddNeighbor(e310);
            e311.AddNeighbor(e312);
            e311.AddNeighbor(l7);
            e312.AddNeighbor(l7);
            e312.AddNeighbor(e311);
            e312.AddNeighbor(d307);
            d307.AddNeighbor(e312);
            d307.AddNeighbor(d308);
            d308.AddNeighbor(d307);
            d308.AddNeighbor(d309);
            d309.AddNeighbor(d308);
            d309.AddNeighbor(d310);
            d310.AddNeighbor(d309);
            d310.AddNeighbor(d311);
            d311.AddNeighbor(d310);
            d311.AddNeighbor(d312);
            d311.AddNeighbor(schodyPierwszeDrugiePietroDrugie);
            d312.AddNeighbor(d311);
            d312.AddNeighbor(schodyPierwszeDrugiePietroDrugie);
            d312.AddNeighbor(d313);
            d312.AddNeighbor(l6);
            d313.AddNeighbor(d312);
            d313.AddNeighbor(d314);
            d313.AddNeighbor(l6);
            d314.AddNeighbor(d313);
            d314.AddNeighbor(l6);
            d314.AddNeighbor(l5);
            l6.AddNeighbor(schodyPierwszeDrugiePietroDrugie);
            l6.AddNeighbor(d312);
            l6.AddNeighbor(d313);
            l6.AddNeighbor(d314);
            l6.AddNeighbor(l5);
            l5.AddNeighbor(l6);
            l5.AddNeighbor(d314);
            l5.AddNeighbor(l4);
            l4.AddNeighbor(l5);
            l4.AddNeighbor(s9);
            l4.AddNeighbor(schodyKoloS9);
            l4.AddNeighbor(korytarzDrugiePietro);
            s9.AddNeighbor(l4);
            s9.AddNeighbor(schodyKoloS9);
            schodyKoloS9.AddNeighbor(schodyPierwszePietroKoloS8);
            schodyKoloS9.AddNeighbor(s9);
            schodyKoloS9.AddNeighbor(l4);
            schodyKoloS9.AddNeighbor(korytarzDrugiePietro);
            korytarzDrugiePietro.AddNeighbor(schodyKoloS9);
            korytarzDrugiePietro.AddNeighbor(l4);
            korytarzDrugiePietro.AddNeighbor(wcDrugiePietro);
            korytarzDrugiePietro.AddNeighbor(korytarzPierwszePietro);
            b317.AddNeighbor(ss3);
            b317.AddNeighbor(pm3);
            b317.AddNeighbor(b318);
            b318.AddNeighbor(b317);
            b318.AddNeighbor(b319);
            b318.AddNeighbor(b308);
            b319.AddNeighbor(b318);
            b319.AddNeighbor(b320);
            b319.AddNeighbor(b308);
            b319.AddNeighbor(b307);
            b320.AddNeighbor(b319);
            b320.AddNeighbor(b321);
            b320.AddNeighbor(b307);
            b320.AddNeighbor(b306);
            b321.AddNeighbor(b320);
            b321.AddNeighbor(b306);
            b321.AddNeighbor(b322);
            b321.AddNeighbor(b307);
            b322.AddNeighbor(b321);
            b322.AddNeighbor(b323);
            b322.AddNeighbor(b306);
            b322.AddNeighbor(b305);
            b322.AddNeighbor(b304);
            b323.AddNeighbor(b322);
            b323.AddNeighbor(b324);
            b323.AddNeighbor(b303);
            b323.AddNeighbor(b304);
            b323.AddNeighbor(b305);
            b324.AddNeighbor(schodyKoloAuliDrugie);
            b324.AddNeighbor(b323);
            b324.AddNeighbor(b302);
            b324.AddNeighbor(b303);
            schodyKoloAuliDrugie.AddNeighbor(schodyKoloAuliPierwsze);
            schodyKoloAuliDrugie.AddNeighbor(b324);
            schodyKoloAuliDrugie.AddNeighbor(b302);
            b302.AddNeighbor(schodyKoloAuliDrugie);
            b302.AddNeighbor(b324);
            b302.AddNeighbor(b303);
            b303.AddNeighbor(b302);
            b303.AddNeighbor(b304);
            b303.AddNeighbor(b324);
            b303.AddNeighbor(b323);
            b304.AddNeighbor(b303);
            b304.AddNeighbor(b305);
            b304.AddNeighbor(b322);
            b304.AddNeighbor(b323);
            b305.AddNeighbor(b304);
            b305.AddNeighbor(b306);
            b305.AddNeighbor(b323);
            b305.AddNeighbor(b322);
            b306.AddNeighbor(b305);
            b306.AddNeighbor(b307);
            b306.AddNeighbor(b320);
            b306.AddNeighbor(b321);
            b306.AddNeighbor(b322);
            b307.AddNeighbor(b306);
            b307.AddNeighbor(b308);
            b307.AddNeighbor(b319);
            b307.AddNeighbor(b320);
            b307.AddNeighbor(b321);
            b308.AddNeighbor(b307);
            b308.AddNeighbor(b318);
            b308.AddNeighbor(b319);
            wcDrugiePietro.AddNeighbor(korytarzDrugiePietro);
            wcDrugiePietro.AddNeighbor(l3);
            l3.AddNeighbor(wcDrugiePietro);
            l3.AddNeighbor(l2);
            l2.AddNeighbor(l3);
            l2.AddNeighbor(l1);
            l1.AddNeighbor(l2);
            l1.AddNeighbor(schodyKoloPM3);
            schodyKoloPM3.AddNeighbor(schodyPierwszePietroKoloPM2);
            schodyKoloPM3.AddNeighbor(pm3);
            schodyKoloPM3.AddNeighbor(l1);
            pm3.AddNeighbor(schodyKoloPM3);
            pm3.AddNeighbor(b317);
            pm3.AddNeighbor(ss3);
            ss3.AddNeighbor(b317);
            ss3.AddNeighbor(pm3);
            f405.AddNeighbor(f403);
            f405.AddNeighbor(f303);
            f405.AddNeighbor(f305);
            f405.AddNeighbor(f306);
            f403.AddNeighbor(f405);
        }

        public void addRoomsToVector()
        {
            //Dodawanie pomieszczen
            GlobalRooms.AddRoom(klubStudencki);
            GlobalRooms.AddRoom(wcPiwnica);
            GlobalRooms.AddRoom(bar);
            GlobalRooms.AddRoom(schodyParterPiwnica);
            GlobalRooms.AddRoom(schodyParterPiwnicaLesk);
            GlobalRooms.AddRoom(lesk);

            GlobalRooms.AddRoom(e106);
            GlobalRooms.AddRoom(e107);
            GlobalRooms.AddRoom(e109);
            GlobalRooms.AddRoom(e111);
            GlobalRooms.AddRoom(wc3);
            GlobalRooms.AddRoom(s3);
            GlobalRooms.AddRoom(s2);
            GlobalRooms.AddRoom(s1);
            GlobalRooms.AddRoom(portiernia);
            GlobalRooms.AddRoom(wejscie);
            GlobalRooms.AddRoom(schodyParterPiwnicaLeskKoloWejscia);
            GlobalRooms.AddRoom(schodyParterPiwnicaKoloPatio);
            GlobalRooms.AddRoom(d114);
            GlobalRooms.AddRoom(d113);
            GlobalRooms.AddRoom(d112);
            GlobalRooms.AddRoom(d111);
            GlobalRooms.AddRoom(d110);
            GlobalRooms.AddRoom(d109);
            GlobalRooms.AddRoom(d108);
            GlobalRooms.AddRoom(d107);
            GlobalRooms.AddRoom(schody3);
            GlobalRooms.AddRoom(biblioteka);
            GlobalRooms.AddRoom(patio2);
            GlobalRooms.AddRoom(galeria);
            GlobalRooms.AddRoom(patio);
            GlobalRooms.AddRoom(b124);
            GlobalRooms.AddRoom(b123);
            GlobalRooms.AddRoom(b122);
            GlobalRooms.AddRoom(b121);
            GlobalRooms.AddRoom(b120);
            GlobalRooms.AddRoom(b119);
            GlobalRooms.AddRoom(aula);
            GlobalRooms.AddRoom(salaKonferencyjna);
            GlobalRooms.AddRoom(schodyKoloAuli);
            GlobalRooms.AddRoom(wc2);
            GlobalRooms.AddRoom(b106);
            GlobalRooms.AddRoom(b107);
            GlobalRooms.AddRoom(b108);
            GlobalRooms.AddRoom(b109);
            GlobalRooms.AddRoom(b110);
            GlobalRooms.AddRoom(b111);
            GlobalRooms.AddRoom(wc);
            GlobalRooms.AddRoom(l13);
            GlobalRooms.AddRoom(c106);
            GlobalRooms.AddRoom(c104);
            GlobalRooms.AddRoom(c102);
            GlobalRooms.AddRoom(schody);
            GlobalRooms.AddRoom(pm1);
            GlobalRooms.AddRoom(ss1);

            GlobalRooms.AddRoom(f209);
            GlobalRooms.AddRoom(f208);
            GlobalRooms.AddRoom(f207);
            GlobalRooms.AddRoom(f206);
            GlobalRooms.AddRoom(f205);
            GlobalRooms.AddRoom(f204);
            GlobalRooms.AddRoom(wc2IPietro);
            GlobalRooms.AddRoom(e207);
            GlobalRooms.AddRoom(e204);
            GlobalRooms.AddRoom(e203);
            GlobalRooms.AddRoom(e202);
            GlobalRooms.AddRoom(s4);
            GlobalRooms.AddRoom(e211);
            GlobalRooms.AddRoom(e212);
            GlobalRooms.AddRoom(e213);
            GlobalRooms.AddRoom(e214);
            GlobalRooms.AddRoom(spot);
            GlobalRooms.AddRoom(schodyKoloWejsciaPierwszePietro);
            GlobalRooms.AddRoom(schodyPierwszeDrugiePietroPierwsze);
            GlobalRooms.AddRoom(dziekanat);
            GlobalRooms.AddRoom(dziekanatStudencki);
            GlobalRooms.AddRoom(s5);
            GlobalRooms.AddRoom(s6);
            GlobalRooms.AddRoom(s7);
            GlobalRooms.AddRoom(s8);
            GlobalRooms.AddRoom(korytarzPierwszePietro);
            GlobalRooms.AddRoom(schodyPierwszePietroKoloS8);
            GlobalRooms.AddRoom(b217);
            GlobalRooms.AddRoom(b218);
            GlobalRooms.AddRoom(b219);
            GlobalRooms.AddRoom(b220);
            GlobalRooms.AddRoom(b221);
            GlobalRooms.AddRoom(b222);
            GlobalRooms.AddRoom(b223);
            GlobalRooms.AddRoom(b224);
            GlobalRooms.AddRoom(schodyKoloAuliPierwsze);
            GlobalRooms.AddRoom(b202);
            GlobalRooms.AddRoom(b203);
            GlobalRooms.AddRoom(b204);
            GlobalRooms.AddRoom(b205);
            GlobalRooms.AddRoom(b206);
            GlobalRooms.AddRoom(b207);
            GlobalRooms.AddRoom(b208);
            GlobalRooms.AddRoom(wcPierwsze);
            GlobalRooms.AddRoom(l12);
            GlobalRooms.AddRoom(l11);
            GlobalRooms.AddRoom(l10);
            GlobalRooms.AddRoom(schodyPierwszePietroKoloPM2);
            GlobalRooms.AddRoom(pm2);
            GlobalRooms.AddRoom(ss2);

            GlobalRooms.AddRoom(l9);
            GlobalRooms.AddRoom(l8);
            GlobalRooms.AddRoom(l7);
            GlobalRooms.AddRoom(schodyPierwszeDrugiePietroDrugie);
            GlobalRooms.AddRoom(e307);
            GlobalRooms.AddRoom(e309);
            GlobalRooms.AddRoom(e310);
            GlobalRooms.AddRoom(e311);
            GlobalRooms.AddRoom(e312);
            GlobalRooms.AddRoom(d307);
            GlobalRooms.AddRoom(d308);
            GlobalRooms.AddRoom(d309);
            GlobalRooms.AddRoom(d310);
            GlobalRooms.AddRoom(d311);
            GlobalRooms.AddRoom(d312);
            GlobalRooms.AddRoom(d313);
            GlobalRooms.AddRoom(d314);
            GlobalRooms.AddRoom(l6);
            GlobalRooms.AddRoom(l5);
            GlobalRooms.AddRoom(l4);
            GlobalRooms.AddRoom(s9);
            GlobalRooms.AddRoom(schodyKoloS9);
            GlobalRooms.AddRoom(korytarzDrugiePietro);
            GlobalRooms.AddRoom(b317);
            GlobalRooms.AddRoom(b318);
            GlobalRooms.AddRoom(b319);
            GlobalRooms.AddRoom(b320);
            GlobalRooms.AddRoom(b321);
            GlobalRooms.AddRoom(b322);
            GlobalRooms.AddRoom(b323);
            GlobalRooms.AddRoom(b324);
            GlobalRooms.AddRoom(schodyKoloAuliDrugie);
            GlobalRooms.AddRoom(b302);
            GlobalRooms.AddRoom(b303);
            GlobalRooms.AddRoom(b304);
            GlobalRooms.AddRoom(b305);
            GlobalRooms.AddRoom(b306);
            GlobalRooms.AddRoom(b307);
            GlobalRooms.AddRoom(b308);
            GlobalRooms.AddRoom(wcDrugiePietro);
            GlobalRooms.AddRoom(l3);
            GlobalRooms.AddRoom(l2);
            GlobalRooms.AddRoom(l1);
            GlobalRooms.AddRoom(schodyKoloPM3);
            GlobalRooms.AddRoom(pm3);
            GlobalRooms.AddRoom(ss3);
            GlobalRooms.AddRoom(f105);
            GlobalRooms.AddRoom(f107);
            GlobalRooms.AddRoom(f108);
            GlobalRooms.AddRoom(f303);
            GlobalRooms.AddRoom(f305);
            GlobalRooms.AddRoom(f306);
            GlobalRooms.AddRoom(f403);
            GlobalRooms.AddRoom(f405);
        }
    }
}
